### ISSUE TITLE
Towards usable

### ISSUE THREAD

**Issue by almarklein** [almarklein/mypaas#2]
## Todo

* [x] Init works
* [x] Can deploy a service
* [x] Zero downtime deploy
* [x] Enable `pip install mypaas[server]`
* [x] Split server and client commands
* [x] Server stats
  * [x] Implement stats server as Docker container
  * [x] Can send data to it over UDP from other container and from host
  * [x] Viz stats
  * [x] Store aggregations using Welford's algorithm to avoid precision loss
  * [x] Re-design the format to specify metrics
  * [x] Make hello-world site example send data to it
  * [ ] Can we make it convert IP's to countries? ->tricky, for later
  * [x] Per-week and/or per-month unique metrics.
  * [x] Make deploy daemon generate some stats data.
  * [x] Tests.
* [x] Also sign the payload, so that an attacker cannot change it.
* [x] Docs
* [x] Tests
* [x] Set expectations
* [x] Options to set memory and cpu limits
* [x] Scaling
* [x] Reboot signal for core services
* [x] Specify private key via an env variable for on CI

## Future

* More tests
* More docs
* Spin out itemdb
* Spin out monitr
